version: '3'
services:
  database-server:
    container_name: database-server
    hostname: database-server
    image: mysql:${MYSQL_VERSION}
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./server/database/conf.d:/etc/mysql/conf.d
      - ./server/database/initdb.d:/docker-entrypoint-initdb.d
      - ./server/database/.tmp/datadir:/var/lib/mysql
      - ./server/database/.tmp/logs:/var/log/mysql
    ports:
    - 3306:3306

  nacos-server:
    container_name: nacos-server
    hostname: nacos-server
    image: nacos/nacos-server:${NACOS_VERSION}
    depends_on:
      - database-server
    restart: always
    environment:
      - JVM_XMS=200m
      - JVM_XMX=200m
      - JVM_XMN=100m
      - JVM_MS=64m
      - JVM_MMS=128m
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=database-server
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    volumes:
      - ./server/nacos/.tmp/logs/:/home/nacos/logs
      - ./server/nacos/.tmp/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
      - 9848:9848
      - 9555:9555

  gateway:
    container_name: gateway
    hostname: gateway
    image: snowball/gateway
    depends_on:
      - nacos-server
    build:
      context: ./gateway
    restart: always
    ports:
      - 8080:8080

  uac-service:
    container_name: uac-service
    hostname: uac-service
    image: snowball/uac-service
    depends_on:
      - nacos-server
    build:
      context: ./service/uac/uac-service
    restart: always
    ports:
      - 9001:9001

  order-service:
    container_name: order-service
    hostname: order-service
    image: snowball/order-service
    depends_on:
      - nacos-server
    build:
      context: ./service/order/order-service
    restart: always
    ports:
      - 9003:9003
