server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: uac-service
          uri: lb://uac-service
          predicates:
            - Path=/uac/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
    jackson:
      property-naming-strategy: SNAKE_CASE
