server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: uac-service
          uri: lb://uac-service
          predicates:
            - Path=/uac/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
