server:
  port: 8080
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Vary, RETAIN_UNIQUE
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: uac-service
          uri: lb://uac-service
          predicates:
            - Path=/uac/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
