server:
  port: 9001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://database-server:3306/snowball_uac?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true
feign:
  hystrix:
    enable: true
mybatis-plus:
  global-config:
    db-config:
      tablePrefix: t_
